numpy:
  - 1.26
libprotobuf:
  - 5.29.3
protobuf:
  - 5.29.3
spdlog:
  - 1.15
pugixml:
  - '1.15'
libopencv:
  - 4.11.0
libxml2:
  - 2.13.*
graphviz:
  - 13.*

tbb:
  - '2021'
tbb_devel:
  - '2021'

# Workaround for https://github.com/RoboStack/ros-jazzy/pull/40#issuecomment-2782226697
cmake:
  - 3.*

cdt_name:  # [linux]
  - conda  # [linux]

python:
  - 3.12.* *_cpython
python_impl:
  - cpython

c_compiler:
  - gcc
c_compiler_version:
  - 14
c_stdlib:
  - sysroot
c_stdlib_version:
  - 2.17
cxx_compiler:
  - gxx
cxx_compiler_version:
  - 14

libzenohc:
  - 1.5.1
libzenohcxx:
  - 1.5.1

libhwloc:
  - 2.11.2
